### ISSUE TITLE
Failed to fetch platform

### ISSUE THREAD

**Issue by freedmo** [apache/cordova-cli#357]
Cordova version:  7.0.1 and 7.1.0
Last time build app was on 09.10.18.
But now when running `npx cordova platform add ios@4.5.4`, I'm getting following error:

```
Error: Failed to fetch platform cordova-ios@4.5.4
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm WARN package.json NAME.app@1.0.0 No repository   ##field.
npm WARN package.json NAME.app@1.0.0 No README data
npm ERR! Darwin 18.0.0
npm ERR! argv "/usr/local/bin/node" "/PATH/node_modules/.bin/npm" "install" "cordova-ios@4.5.4" "--save"
npm ERR! node v8.12.0
npm ERR! npm  v2.15.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package acorn@5.7.3 does not satisfy its siblings' peerDependencies requirements!
```

Found that [ticket](https://github.com/browserify/acorn-node/issues/4) of acorn package.

Any work around?

**Comment by dpogue** [comment]
Updating to Cordova 8.1.2 should fix the problem.

Cordova 8+ use the system npm version, whereas Cordova 7 is using npm 2, which has different rules around peerDependencies.

**Comment by genox** [comment]
Same problem, same error message. Updating Cordova does not fix this issue.

I updated to Cordova 8.1.2 but it still uses npm 2.15.12 instead of system npm which is 6.4.1. Is there a way to force Cordova to use a specific version of npm?

**Comment by janpio** [comment]
Are you sure the update worked @genox? Does `cordova- v` return 8.1.2?

**Comment by dpogue** [comment]
If you have a package-lock.json file, it's possible that npm@2.12 is listed in there. Try deleting the package-lock file and re-running `npm install`.

**Comment by genox** [comment]
@janpio Yes, `cordova -v` returns 8.1.2.
@dpogue Yes, `rm -rf package-lock.json node_modules` multiple times, followed by `npm i` etc. But you're right, something's probably installing npm 2 but could be anything. Will check tomorrow wether package-lock contains npm 2 and will try to figure why the heck it's there in the first place.

**Comment by dpogue** [comment]
`npm ls npm` might help identify where that dependency is coming from

**Comment by dpa99c** [comment]
workaround: run `npm install acorn` in the Cordova project directory.
that should install `acorn@6` and that fixes the error for me (using `cordova@8.1.2`)

**Comment by brodybits** [comment]
@dpa99c thanks for the workaround. But we still do not seem to have a way to reproduce the reported issue. Not on Cordova 8, not on Cordova 7. Here you can see it works for me on Cordova 7:

```
Brodys-MacBook-Pro:cordova brodybits$ cordova --version
7.1.0
Brodys-MacBook-Pro:cordova brodybits$ cordova create ctt2
Creating a new cordova project.
Brodys-MacBook-Pro:cordova brodybits$ cd ctt2
Brodys-MacBook-Pro:ctt2 brodybits$ cordova platform add ios@4.5.4
Using cordova-fetch for cordova-ios@4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: io.cordova.hellocordova
	Name: HelloCordova
iOS project created with cordova-ios@4.5.4
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving ios@~4.5.4 into config.xml file ...
```

A project that can demonstrate the reported issue for us would be extremely helpful.

**Comment by brodybits** [comment]
@dpa99c thanks!

@genox thanks for the helpful info. (I edited your comment to use 3 backticks to show your `npm ls npm` output more clearly.)

**Comment by dpa99c** [comment]
@genox I've [unpinned the cordova version](https://github.com/dpa99c/cordova-check-plugins/commit/61bdf10b423d09a3a06af0dd47c0c0095c225b5a) in dependencies of `cordova-check-plugins` (my package, my bad) and published a patch version to npm as `cordova-check-plugins@4.0.4` - should resolve your issue, though global installation is recommended as it's a CLI tool (as is `cordova`)

**Comment by DjulLau** [comment]
Had this problem trying to rebuild and old **ionic v1** project. 
After wasting a lot of time I found out I had to remove **```ionic-app-lib```** from ```package.json``` ([needed only for cli v2](https://github.com/ionic-team/ionic-app-lib)), which of course I didn't know... 
This thread helped me a lot (especially the ```npm ls npm``` command). Thanks you guys !

**Comment by HarelM** [comment]
I'm having a similar issue.
I have recently added this plug-in:
https://github.com/j3k0/cordova-plugin-openwith
And my CI started failing with this `fetch` error.
I'll look into the `npm ls npm` but the problem is that my local version is not failing... :-/
Build log can be seen here:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/21746860/job/v1lsmu3teyl72yk0
If anyone has some insights I'll be happy to hear :-)
Relevant project is here:
https://github.com/IsraelHikingMap/Site/tree/master/IsraelHiking.Web

**Comment by HarelM** [comment]
In my recent builds I added `npm ls npm` but I empty (which I believe is a good outcome) but still cordova-fetch fails... I don't know how to debug this... any help will be appreciated...

**Comment by HarelM** [comment]
@dpogue can you elaborate on your theory? Why would adding a single plugin would raise this issue?

**Comment by raphinesse** [comment]
The original issue seems to have been resolved.

**Comment by Sampath-Lokuge** [comment]
This helped to me: https://github.com/apache/cordova-android/issues/803#issuecomment-519629272
