### ISSUE TITLE
Error: Command failed: wmic os get Caption 'wmic' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by originalnoob** [apache/cordova-cli#434]
# Bug Report

### What does actually happen?
Im getting this error after I updated to cordova 9.0.0

```
C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\execa\index
.js:347
                throw err;
                ^

Error: Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.


    at makeError (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_m
odules\execa\index.js:174:9)
    at Function.module.exports.sync (C:\Users\admin\AppData\Roaming\npm\node_mod
ules\cordova\node_modules\execa\index.js:338:15)
    at windowsRelease (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\n
ode_modules\windows-release\index.js:34:24)
    at osName (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modu
les\os-name\index.js:39:18)
    at new Insight (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node
_modules\insight\lib\index.js:37:13)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\cordo
va\src\telemetry.js:26:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
```

### Command or Code
cordova -v
cordova help
cordova build android

### Version information
Cordova 9.0.0
Window 7 64x

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by janpio** [comment]
What version of Windows are you using?
Anything strange about your Windows installation?

**Comment by janpio** [comment]
Related: https://github.com/sindresorhus/windows-release/issues/10

Do you have `c:\Windows\System32\wbem\WMIC.exe`? Then this might help: https://superuser.com/a/1434268/25933

**Comment by originalnoob** [comment]
> Anything strange about your Windows installation?

it

> Anything strange about your Windows installation?

Uhmmm its not original copy

**Comment by MaryemZOBI** [comment]
thanks @janpio,
 adding "c:\Windows\System32\wbem" to my path environnement variable solved this problem

**Comment by prashanthrpr** [comment]
> thanks @janpio,
> adding "c:\Windows\System32\wbem" to my path environnement variable solved this problem

 I have added this but still iam getting the same error!   Even ionic info is not working. iam using windows-10 & ionic v-4.

**Comment by fikalefaza** [comment]
my problem is the same, and solved with this
cmd-->

alias ionic="cmd //C ionic $*"
  alias cordova="cmd //C cordova $*"

**Comment by lokibhardwaj** [comment]
adding "c:\Windows\System32\wbem" to my path environnement variable solved this problem
Also restart your cmd

**Comment by MohammadAsef2019** [comment]
Hello dear friends, I have such a problem too but it did not solve with this path now what should I do?
I use ionic v5 and Cordova v9

**Comment by IsaiahTek** [comment]
I have the same problem.
I tried commenting out the line (347) throwing the error and it worked

**Comment by Nazehs** [comment]
I have the same issue for days now

**Comment by ArthurHNL** [comment]
For me, this issue started occurring when I enabled Windows Credential Guard on my device. It should also be noted that the entire `wmic` utility is deprecated:

![image](https://user-images.githubusercontent.com/31919595/74105491-8cd50080-4b5e-11ea-8a91-81de25db9fa5.png)


My opinion here is that Cordova is relying on a deprecated Windows component that may show undefined behaviour now and in the future since Microsoft will not keep testing whether new Windows versions and / or features might break it.

I found that this command can replace the call to wmic alltogether: 

`powershell (Get-CimInstance -Class Win32_OperatingSystem).Caption`

I'll file an issue for this at the repository for the WindowsRelease module.

**Comment by ArthurHNL** [comment]
Filed this issue: https://github.com/sindresorhus/windows-release/issues/14.

**Comment by landsfiskalen** [comment]
I've made a pull request with a fix that uses powershell where wmic fails. Hoping it gets accepted. If not I cloned the repo and made a new version using the fix. Don't know if it's of any help to anyone, but here's the node package:

https://www.npmjs.com/package/windows-release-ps

**Comment by landsfiskalen** [comment]
[sindresorhus](https://github.com/sindresorhus) have accepted my PR, so "windows-release" should be updated soon, and everything should be working again.

https://github.com/sindresorhus/windows-release/pull/15

**Comment by rars15** [comment]
I ALSO WORK WHEN ADD TO THE PATH " c:\Windows\System32\wbem"
Thank's alot dude !!! win10 64bit

**Comment by Abxabx** [comment]
Finally after 2 days of trying everything imaginable i though that it was covid19. 
IT WORKS !!!  ADD TO PATH " c:\Windows\System32\wbem"
Thanks!!  win10 64bit.

**Comment by devsalimsulaiman** [comment]
It worked for me. I fixed it by adding C:\Windows\System32\wbem to my environment path. Windows 8.
Now cordova -v works well for me.

**Comment by ArthurHNL** [comment]
The underlying issue here is not whether or not `wmic` is on the path or not, the issue is that it is deprecated and may show undefined behaviour.

**Comment by landsfiskalen** [comment]
Just like @ArthurHNL says, adding wbem to the system path won’t work in future Windows releases since WMIC is deprecated. That’s why the windows-release package was updated to use Powershell I stead of WMIC as the first choice.

**Comment by sbairagi** [comment]
I am also getting this error and i was add path in system variables but it's not resolve 
Cordova -v getting this error

**Comment by sbairagi** [comment]
> Finally after 2 days of trying everything imaginable i though that it was covid19.
> IT WORKS !!! ADD TO PATH " c:\Windows\System32\wbem"
> Thanks!! win10 64bit.

Please help me out I am also getting this error in Windows 10 64bit
How to resolve this

**Comment by breautek** [comment]
After you change environment variables, you must restart your terminal.

**Comment by sbairagi** [comment]
i am also restart terminal as well as restart the machine 

its not working yet

**Comment by sbairagi** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/55846799/84992748-ef21bb80-b165-11ea-93e1-38a172468083.png)

**Comment by sbairagi** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/55846799/84993023-50498f00-b166-11ea-82fa-dd18a96b9164.png)

**Comment by sbairagi** [comment]
i am solved this error but i don know its right or not i am commenting the line who gives me the error 

path  C:\Users\sbair\AppData\Roaming\npm\node_modules\cordova\node_modules\execa\index.js line no 347 and commenting // throw err;

and then run cordova -v on terminal its running

**Comment by breautek** [comment]
`c:\Windows\System32\wbem` is suppose to be added to the `Path` variable, not a `cordova` variable. `Path` contains several paths, separated by a semicolon.

Prepend it with `c:\Windows\System32\wbem;<your existing path here>`

**Comment by sbairagi** [comment]
> `c:\Windows\System32\wbem` is suppose to be added to the `Path` variable, not a `cordova` variable. `Path` contains several paths, separated by a semicolon.
> 
> Prepend it with `c:\Windows\System32\wbem;<your existing path here>`

thank you brother its working i am not put in the path variable i am creating a another variable

**Comment by Ashvith** [comment]
For all of you out there, if this probem still persists:
Add the following directory to the 'Path' variables in System Variable (or User variable, depends on you)
C:\Windows\System32\wbem

**Comment by Aneeqa-Rajput** [comment]
@janpio thanks alot Sir

**Comment by ArthurHNL** [comment]
A fix for this issue is on it's way (Cordova only needs to update the `windows-release` package). A possible workaround (adding `wbem` to the path) is known (even though it is not exactly related to this issue, this would more rather mean that your Windows installation is corrupt). I suggest locking this issue because there is no longer any relevant discussion here.

**Comment by raphinesse** [comment]
Any fresh Cordova installation should have the version of windows-release that has the fix, due to compatible semver ranges. No need to change your PATH.

If you still encounter this problem, re-install Cordova and check that the version of windows-release used by it is at least 3.3.0.

**Comment by Nagaraju-Y** [comment]
I've tried all the above methods and it didn't help me. I just re-installed Cordova and it got changed from V9.0.0 to V10.0.0. Then it worked
